version: '2'

services:

  bro:
    image: anurag1591/bro_dev_bro:latest
    container_name: bro
    user: root
    volumes:
      - ./etc/broctl.cfg:/usr/local/bro/etc/broctl.cfg
      - ./etc/node.cfg:/usr/local/bro/etc/node.cfg
      - ./etc/networks.cfg:/usr/local/bro/etc/networks.cfg
      - ./etc/filebeat.yml:/etc/filebeat/filebeat.yml
      - ./site/local.bro:/usr/local/bro/share/bro/site/local.bro
      - ./logs/:/usr/local/bro/spool/manager
    ports:
      - "5044:5044"
    network_mode: "host"
    command: bash -c "broctl install ; broctl deploy && service filebeat start ; tail -f /dev/null"
