---
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml
#
cluster.name: "docker-cluster"
network.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1
#discovery.type: single-node
# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288

## Use single node discovery in order to disable production mode and avoid bootstrap checks
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
#
## Threadpool Settings ##

# Search pool
#threadpool.search.type: fixed
#threadpool.search.size: 20
#threadpool.search.queue_size: 100

# Bulk pool
#threadpool.bulk.type: fixed
#threadpool.bulk.size: 60
#threadpool.bulk.queue_size: 300

# Index pool
#threadpool.index.type: fixed
#threadpool.index.size: 20
#threadpool.index.queue_size: 100

# Indices settings
#indices.memory.index_buffer_size: 30%
#indices.memory.min_shard_index_buffer_size: 12mb
#indices.memory.min_index_buffer_size: 96mb
#
# Cache Sizes
#indices.fielddata.cache.size: 15%
#indices.fielddata.cache.expire: 6h
#indices.cache.filter.size: 15%
#indices.cache.filter.expire: 6h

# Indexing Settings for Writes


# Minimum nodes alive to constitute an operational cluster

xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true
